### ISSUE TITLE
External Template Snippets are not working with Partials

### ISSUE THREAD

**Issue by mkurz** [mmurray/play-mustache#1]
Hi!

I have the following two mustache templates:

<b>app/views/mustaches/my_template.html</b>

```
<li id="client_{{id}}">
    <span>Client {{id}}</span>
    <span>{{firstname}}</span>
    {{> app/views/mustaches/to_include}}
</li>
```

<b>app/views/mustaches/to_include.html</b>
    <span>{{lastname}}</span>

In a play view I write:
    <ul id="clients">
        #{list clients, as: 'client'}
            #{mustache.print 'my_template.html', context:client /}
        #{/list}
    </ul>
which works.

In JavaScript I write:
    var html = PlayMustache.to_html('my_template.html', clientobject);
    $('body').append($(html));

which <b>doesn't</b> work!
For a client with the id=29, firstname=Joseph, lastname=Kissinger
it gives me the line:
    "Person 29 Joseph {{> app/views/mustaches/to_include}}"

This means it does not include the (sub)template file correctly.

Is there a workaround for this or can this easily be fixed?

Also, I think it would be much more comfortable to write only
    {{> to_include.html}}
or
    {{> to_include}}
instead of
    {{> app/views/mustaches/to_include}}

**Comment by mmurray** [comment]
Thanks for the suggestions.

I added client-side support for partials, and I made the server-side partials relative to /app/views/mustaches (or relative to your custom `mustache.dir` if you have one set).

So `{{>to_include}}` should work both in Play and in JavaScript.

I'm about to publish these changes to the Play module repository as version 0.2
